cd community && \
uv run vibevoice/finetune/train_vibevoice.py \
    --model_name_or_path ../vibevoice_1.5b \
    --dataset_name /home/administrator/VibeVoice/vibevoice_dataset/zoengjyutgaai/lukdinggei \
    --text_column_name text \
    --audio_column_name audio \
    --voice_prompt_source other \
    --target_feature_cache_dir ../vibevoice_dataset/feature_cache \
    --output_dir ../vibevoice_1.5b_cantonese_train \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --dataloader_num_workers 8 \
    --dataloader_persistent_workers True \
    --dataloader_pin_memory True \
    --dataloader_prefetch_factor 4 \
    --optim adamw_torch_fused \
    --attn_implementation sdpa \
    --learning_rate 2.5e-5 \
    --num_train_epochs 3 \
    --logging_steps 10 \
    --save_steps 250 \
    --save_total_limit 3 \
    --report_to mlflow \
    --remove_unused_columns False \
    --bf16 True \
    --do_train \
    --gradient_clipping \
    --gradient_checkpointing False \
    --ddpm_batch_mul 4 \
    --diffusion_loss_weight 1.4 \
    --train_diffusion_head True \
    --ce_loss_weight 0.1 \
    --voice_prompt_drop_rate 0.2 \
    --lora_target_modules q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj \
    --lr_scheduler_type cosine \
    --warmup_ratio 0.03 \
    --max_grad_norm 0.8
